/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/catalog/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search every category with the kernel filters */
        get: operations["searchCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/listings/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match counts per category and city
         * @description Takes the filter parameters of `searchCatalog`; `sort`, `page` and `pageSize` are ignored. Each facet excludes its own filter.
         */
        get: operations["getCatalogFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/listings/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Featured and verified listings across categories, newest first */
        get: operations["getFeaturedListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/listings/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Newest listings across categories, optionally one category */
        get: operations["getRecentListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own listings
         * @description The caller's own listings in every status by default; `status` narrows. Sort is fixed:
         *     `published_at DESC NULLS LAST, created_at DESC`.
         *     The seller is the token's `sub`, never a request value.
         */
        get: operations["getMyListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/property/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search property listings with the property filters */
        get: operations["searchPropertyListings"];
        put?: never;
        /**
         * Publish a property listing
         * @description Requires a Supabase access token and a seller profile (`PUT /v1/me/profile`, else 422).
         *     `id`, `status = active`, `featured = false`, `verified = false`, `sellerId` (the token's `sub`)
         *     and `publishedAt` are set by the server. Every image path must have been issued to the same
         *     user by `POST /v1/media/upload-url`. `subcategory` × `deal` must be an allowed pair and
         *     `price.period` must follow `deal` (sale → total, rent → month, daily → night).
         */
        post: operations["createPropertyListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/property/listings/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match counts per subcategory, deal, condition and city; each facet excludes its own filter
         * @description Takes the filter parameters of `searchPropertyListings`; `sort`, `page` and `pageSize` are ignored.
         */
        get: operations["getPropertyFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/property/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a property listing by id, with its seller */
        get: operations["getPropertyListingById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/property/listings/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active listings with the same subcategory, deal and city, newest first */
        get: operations["getSimilarPropertyListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's seller profile */
        get: operations["getMyProfile"];
        /**
         * Create or replace the caller's seller profile
         * @description Upsert keyed by the token's `sub`. `memberSince` is set on first creation and never changes. `avatarPath` must be an object path issued by `POST /v1/media/upload-url` with `purpose = avatar`.
         */
        put: operations["putMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign a Supabase Storage upload URL for one image
         * @description Returns a signed URL the client `PUT`s the file bytes to (with its `Content-Type` header),
         *     plus the `objectPath` to send back in a listing's `images` or a profile's `avatarPath`.
         *     Image bytes never pass through this API. Signed URLs are valid for two hours.
         */
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Every reserved category name (ADR 0006); only `LaunchCategory` values appear in responses
         * @enum {string}
         */
        Category: "property" | "jobs" | "vehicles" | "services" | "businesses" | "goods" | "agro";
        /** @enum {string} */
        LaunchCategory: "property" | "jobs" | "vehicles" | "services";
        /** @enum {string} */
        Currency: "USD" | "AMD";
        /** @enum {string} */
        PricePeriod: "total" | "month" | "night" | "hour";
        /** @enum {string} */
        ListingStatus: "draft" | "active" | "archived" | "closed";
        /** @enum {string} */
        SellerType: "private" | "agency" | "dealer" | "company";
        /** @enum {string} */
        City: "kapan" | "goris" | "sisian" | "kajaran" | "meghri" | "agarak" | "dastakert" | "tatev" | "khndzoresk" | "shinuhayr";
        /** @enum {string} */
        District: "kapan-center" | "kapan-vachagan" | "kapan-achanan" | "kapan-shahumyan" | "kapan-dzork" | "kapan-kavart" | "kapan-aghbyur" | "goris-center" | "goris-verin-goris" | "goris-aghbyur" | "goris-davit-bek" | "goris-syunik" | "sisian-center" | "sisian-arevik" | "sisian-norashen" | "sisian-sisakan" | "kajaran-center" | "kajaran-norashen" | "kajaran-lernayin" | "meghri-center" | "meghri-prkashen" | "meghri-mets-tagh" | "agarak-center" | "agarak-gortsaranayin" | "dastakert-center" | "tatev-center" | "tatev-vorotan-gorge" | "khndzoresk-center" | "khndzoresk-hin-khndzoresk" | "shinuhayr-center";
        /**
         * @description `relevant` = featured first, then newest (with `q`: text rank first)
         * @enum {string}
         */
        SortKey: "relevant" | "date-desc" | "price-asc" | "price-desc";
        /** @enum {string} */
        PropertySubcategory: "apartments" | "houses" | "new-buildings" | "commercial" | "land" | "garages" | "hotels" | "guesthouses";
        /**
         * @description Allowed per subcategory: apartments/houses all three; new-buildings sale; commercial/land/garages sale+rent; hotels/guesthouses daily
         * @enum {string}
         */
        Deal: "sale" | "rent" | "daily";
        /** @enum {string} */
        PropertyCondition: "euro" | "renovated" | "good" | "needs-repair" | "shell";
        /** @enum {string} */
        BuildingType: "new" | "secondary";
        /** @enum {string} */
        PropertySortKey: "relevant" | "date-desc" | "price-asc" | "price-desc" | "area-desc";
        /**
         * @description Filter chips; `0` is a studio, `4` means four or more
         * @enum {string}
         */
        RoomsOption: "0" | "1" | "2" | "3" | "4";
        /** @enum {string} */
        LandType: "residential" | "agricultural" | "commercial" | "industrial" | "recreational";
        Money: {
            /**
             * Format: int64
             * @description Whole units of `currency`; `null` only when `negotiable` is true
             */
            amount: number | null;
            currency: components["schemas"]["Currency"];
            period: components["schemas"]["PricePeriod"];
            negotiable: boolean;
        };
        Coords: {
            lat: number;
            lng: number;
        };
        SellerSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["SellerType"];
            /** Format: uri */
            avatarUrl?: string;
            /** @example +37491234567 */
            phone: string;
            hasWhatsApp: boolean;
            hasTelegram: boolean;
            hasViber: boolean;
            /** Format: date-time */
            memberSince: string;
        };
        SellerProfile: components["schemas"]["SellerSummary"];
        PutMyProfileRequest: {
            name: string;
            type: components["schemas"]["SellerType"];
            phone: string;
            hasWhatsApp: boolean;
            hasTelegram: boolean;
            hasViber: boolean;
            /** @description A Storage object path issued with `purpose = avatar` */
            avatarPath?: string;
        };
        /** @description `{ <param>: { <value>: count } }` for every faceted filter of the category, zeros included */
        Facets: {
            [key: string]: {
                [key: string]: number;
            };
        };
        CatalogCard: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sellerId: string;
            category: components["schemas"]["LaunchCategory"];
            subcategory: string;
            title: string;
            price: components["schemas"]["Money"];
            city: components["schemas"]["City"];
            district?: components["schemas"]["District"];
            /** Format: uri */
            coverImage?: string;
            imageCount: number;
            featured: boolean;
            verified: boolean;
            status: components["schemas"]["ListingStatus"];
            /** Format: date-time */
            publishedAt: string;
            /** @description Per category (spec §4.8): property `{deal, rooms, area, landArea}`; jobs `{employer, employmentType, experience}`; vehicles `{brand, model, year, mileage, fuel}`; services `{travelsToClient}` */
            card: {
                [key: string]: unknown;
            };
        };
        CatalogCardPage: {
            items: components["schemas"]["CatalogCard"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PropertyFields: {
            /** @description 0 = studio. Required for apartments, houses, new-buildings, hotels, guesthouses; forbidden for land, garages */
            rooms?: number;
            /** @description m². Required for every subcategory but land */
            area?: number;
            /** @description sotka (100 m²). Required for land; forbidden for apartments, new-buildings, garages, hotels, guesthouses */
            landArea?: number;
            /** @description Only when subcategory = land */
            landType?: components["schemas"]["LandType"];
            /** @description Forbidden for houses, land, garages, hotels, guesthouses */
            floor?: number;
            /** @description Forbidden for land, garages, hotels, guesthouses (houses = storeys) */
            totalFloors?: number;
            condition?: components["schemas"]["PropertyCondition"];
            buildingType?: components["schemas"]["BuildingType"];
            buildYear?: number;
            ceilingHeight?: number;
            bathrooms?: number;
            furniture?: boolean;
            balcony?: boolean;
            parking?: boolean;
            pool?: boolean;
            /** @description Only when subcategory is land or garages */
            water?: boolean;
            /** @description Only when subcategory is land or garages */
            gas?: boolean;
            /** @description Only when subcategory is land or garages */
            electricity?: boolean;
            /** @description Only when subcategory is land or garages */
            pit?: boolean;
        };
        PropertyListing: {
            /** Format: uuid */
            id: string;
            /** @constant */
            category: "property";
            subcategory: components["schemas"]["PropertySubcategory"];
            deal: components["schemas"]["Deal"];
            title: string;
            description: string;
            price: components["schemas"]["Money"];
            city: components["schemas"]["City"];
            district?: components["schemas"]["District"];
            address?: string;
            coords?: components["schemas"]["Coords"];
            images: string[];
            featured: boolean;
            verified: boolean;
            status: components["schemas"]["ListingStatus"];
            /** Format: date-time */
            publishedAt: string;
            seller?: components["schemas"]["SellerSummary"];
        } & components["schemas"]["PropertyFields"];
        PropertyListingPage: {
            items: components["schemas"]["PropertyListing"][];
            page: number;
            pageSize: number;
            total: number;
        };
        CreatePropertyListingRequest: {
            subcategory: components["schemas"]["PropertySubcategory"];
            deal: components["schemas"]["Deal"];
            title: string;
            description: string;
            price: components["schemas"]["Money"];
            city: components["schemas"]["City"];
            district?: components["schemas"]["District"];
            address?: string;
            coords?: components["schemas"]["Coords"];
            images: string[];
        } & components["schemas"]["PropertyFields"];
        CreateUploadUrlRequest: {
            fileName: string;
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
            /**
             * @default listing
             * @enum {string}
             */
            purpose: "listing" | "avatar";
        };
        CreateUploadUrlResponse: {
            /** Format: uri */
            uploadUrl: string;
            token: string;
            objectPath: string;
            /** @constant */
            method: "PUT";
            /** Format: date-time */
            expiresAt: string;
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            traceId?: string;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description RFC 9457 problem with `errors` keyed by parameter or field name */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description RFC 9457 problem, `type = urn:insyunik:error:<module>.not-found` */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Missing, expired, HS256-signed or wrong-audience token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The caller has no seller profile yet (`type = urn:insyunik:error:property.profile-required`) */
        ProfileRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Write rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Full-text search over title, description and address (whole words) */
        q: string;
        /** @description Comma-separated launch categories */
        category: string;
        /** @description Comma-separated city slugs */
        city: string;
        /** @description A district slug (carries its city); must belong to one of the selected cities when `city` is present */
        district: components["schemas"]["District"];
        /** @description Inclusive lower bound on `price.amount` in the listing's own currency */
        priceMin: number;
        priceMax: number;
        /** @description Restrict to one currency */
        cur: components["schemas"]["Currency"];
        /** @description `1` or `true` keeps only listings with at least one image */
        withPhoto: "1" | "true" | "0" | "false";
        verifiedOnly: "1" | "true" | "0" | "false";
        /** @description Comma-separated listing ids in canonical dashed form, at most 50; unknown or inactive ids are omitted. An empty value is no filter, so a client with no ids skips the call. */
        ids: string;
        sort: components["schemas"]["SortKey"];
        propertySort: components["schemas"]["PropertySortKey"];
        page: number;
        pageSize: number;
        limit: number;
        listingId: string;
        /** @description Comma-separated property subcategories */
        propertySubcategory: string;
        /** @description Comma-separated deals */
        deal: string;
        /** @description Comma-separated room counts from `RoomsOption`; `4` means four or more */
        rooms: string;
        areaMin: number;
        areaMax: number;
        floorMin: number;
        floorMax: number;
        totalFloorsMin: number;
        totalFloorsMax: number;
        /** @description Comma-separated conditions */
        condition: string;
        buildingType: components["schemas"]["BuildingType"];
        furniture: "1" | "true" | "0" | "false";
        balcony: "1" | "true" | "0" | "false";
        parking: "1" | "true" | "0" | "false";
        pool: "1" | "true" | "0" | "false";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchCatalog: {
        parameters: {
            query?: {
                /** @description Full-text search over title, description and address (whole words) */
                q?: components["parameters"]["q"];
                /** @description Comma-separated launch categories */
                category?: components["parameters"]["category"];
                /** @description Comma-separated city slugs */
                city?: components["parameters"]["city"];
                /** @description A district slug (carries its city); must belong to one of the selected cities when `city` is present */
                district?: components["parameters"]["district"];
                /** @description Inclusive lower bound on `price.amount` in the listing's own currency */
                priceMin?: components["parameters"]["priceMin"];
                priceMax?: components["parameters"]["priceMax"];
                /** @description Restrict to one currency */
                cur?: components["parameters"]["cur"];
                /** @description `1` or `true` keeps only listings with at least one image */
                withPhoto?: components["parameters"]["withPhoto"];
                verifiedOnly?: components["parameters"]["verifiedOnly"];
                /** @description Comma-separated listing ids in canonical dashed form, at most 50; unknown or inactive ids are omitted. An empty value is no filter, so a client with no ids skips the call. */
                ids?: components["parameters"]["ids"];
                sort?: components["parameters"]["sort"];
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page of cards and the total match count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogCardPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    getCatalogFacets: {
        parameters: {
            query?: {
                /** @description Full-text search over title, description and address (whole words) */
                q?: components["parameters"]["q"];
                /** @description Comma-separated launch categories */
                category?: components["parameters"]["category"];
                /** @description Comma-separated city slugs */
                city?: components["parameters"]["city"];
                /** @description A district slug (carries its city); must belong to one of the selected cities when `city` is present */
                district?: components["parameters"]["district"];
                /** @description Inclusive lower bound on `price.amount` in the listing's own currency */
                priceMin?: components["parameters"]["priceMin"];
                priceMax?: components["parameters"]["priceMax"];
                /** @description Restrict to one currency */
                cur?: components["parameters"]["cur"];
                /** @description `1` or `true` keeps only listings with at least one image */
                withPhoto?: components["parameters"]["withPhoto"];
                verifiedOnly?: components["parameters"]["verifiedOnly"];
                /** @description Comma-separated listing ids in canonical dashed form, at most 50; unknown or inactive ids are omitted. An empty value is no filter, so a client with no ids skips the call. */
                ids?: components["parameters"]["ids"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `{ category: {…}, city: {…} }`, every value present, zeros included */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    getFeaturedListings: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to `limit` cards (default 8) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogCard"][];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    getRecentListings: {
        parameters: {
            query?: {
                category?: components["schemas"]["LaunchCategory"];
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to `limit` cards (default 8) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogCard"][];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    getMyListings: {
        parameters: {
            query?: {
                status?: components["schemas"]["ListingStatus"];
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's own listings, sorted for their own listings screen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogCardPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    searchPropertyListings: {
        parameters: {
            query?: {
                /** @description Full-text search over title, description and address (whole words) */
                q?: components["parameters"]["q"];
                /** @description Comma-separated city slugs */
                city?: components["parameters"]["city"];
                /** @description A district slug (carries its city); must belong to one of the selected cities when `city` is present */
                district?: components["parameters"]["district"];
                /** @description Inclusive lower bound on `price.amount` in the listing's own currency */
                priceMin?: components["parameters"]["priceMin"];
                priceMax?: components["parameters"]["priceMax"];
                /** @description Restrict to one currency */
                cur?: components["parameters"]["cur"];
                /** @description `1` or `true` keeps only listings with at least one image */
                withPhoto?: components["parameters"]["withPhoto"];
                verifiedOnly?: components["parameters"]["verifiedOnly"];
                /** @description Comma-separated property subcategories */
                subcategory?: components["parameters"]["propertySubcategory"];
                /** @description Comma-separated deals */
                deal?: components["parameters"]["deal"];
                /** @description Comma-separated room counts from `RoomsOption`; `4` means four or more */
                rooms?: components["parameters"]["rooms"];
                areaMin?: components["parameters"]["areaMin"];
                areaMax?: components["parameters"]["areaMax"];
                floorMin?: components["parameters"]["floorMin"];
                floorMax?: components["parameters"]["floorMax"];
                totalFloorsMin?: components["parameters"]["totalFloorsMin"];
                totalFloorsMax?: components["parameters"]["totalFloorsMax"];
                /** @description Comma-separated conditions */
                condition?: components["parameters"]["condition"];
                buildingType?: components["parameters"]["buildingType"];
                furniture?: components["parameters"]["furniture"];
                balcony?: components["parameters"]["balcony"];
                parking?: components["parameters"]["parking"];
                pool?: components["parameters"]["pool"];
                sort?: components["parameters"]["propertySort"];
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested page and the total match count; items carry no `seller` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyListingPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    createPropertyListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyListingRequest"];
            };
        };
        responses: {
            /** @description Created, with the seller summary embedded */
            201: {
                headers: {
                    /** @description `/v1/property/listings/{id}` */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyListing"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ProfileRequired"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getPropertyFacets: {
        parameters: {
            query?: {
                /** @description Full-text search over title, description and address (whole words) */
                q?: components["parameters"]["q"];
                /** @description Comma-separated city slugs */
                city?: components["parameters"]["city"];
                /** @description A district slug (carries its city); must belong to one of the selected cities when `city` is present */
                district?: components["parameters"]["district"];
                /** @description Inclusive lower bound on `price.amount` in the listing's own currency */
                priceMin?: components["parameters"]["priceMin"];
                priceMax?: components["parameters"]["priceMax"];
                /** @description Restrict to one currency */
                cur?: components["parameters"]["cur"];
                /** @description `1` or `true` keeps only listings with at least one image */
                withPhoto?: components["parameters"]["withPhoto"];
                verifiedOnly?: components["parameters"]["verifiedOnly"];
                /** @description Comma-separated property subcategories */
                subcategory?: components["parameters"]["propertySubcategory"];
                /** @description Comma-separated deals */
                deal?: components["parameters"]["deal"];
                /** @description Comma-separated room counts from `RoomsOption`; `4` means four or more */
                rooms?: components["parameters"]["rooms"];
                areaMin?: components["parameters"]["areaMin"];
                areaMax?: components["parameters"]["areaMax"];
                floorMin?: components["parameters"]["floorMin"];
                floorMax?: components["parameters"]["floorMax"];
                totalFloorsMin?: components["parameters"]["totalFloorsMin"];
                totalFloorsMax?: components["parameters"]["totalFloorsMax"];
                /** @description Comma-separated conditions */
                condition?: components["parameters"]["condition"];
                buildingType?: components["parameters"]["buildingType"];
                furniture?: components["parameters"]["furniture"];
                balcony?: components["parameters"]["balcony"];
                parking?: components["parameters"]["parking"];
                pool?: components["parameters"]["pool"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `{ subcategory, deal, condition, city }` → `{ value: count }`, zeros included */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    getPropertyListingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listing; only `status = active` listings are visible */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyListing"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSimilarPropertyListings: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path: {
                id: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to `limit` listings (default 4), excluding the anchor; empty when none */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyListing"][];
                };
            };
            400: components["responses"]["ValidationProblem"];
            404: components["responses"]["NotFound"];
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutMyProfileRequest"];
            };
        };
        responses: {
            /** @description The profile after the write */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerProfile"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Signed upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadUrlResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const categoryValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Category"]> = ["property", "jobs", "vehicles", "services", "businesses", "goods", "agro"];
export const launchCategoryValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LaunchCategory"]> = ["property", "jobs", "vehicles", "services"];
export const currencyValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Currency"]> = ["USD", "AMD"];
export const pricePeriodValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PricePeriod"]> = ["total", "month", "night", "hour"];
export const listingStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ListingStatus"]> = ["draft", "active", "archived", "closed"];
export const sellerTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SellerType"]> = ["private", "agency", "dealer", "company"];
export const cityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["City"]> = ["kapan", "goris", "sisian", "kajaran", "meghri", "agarak", "dastakert", "tatev", "khndzoresk", "shinuhayr"];
export const districtValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["District"]> = ["kapan-center", "kapan-vachagan", "kapan-achanan", "kapan-shahumyan", "kapan-dzork", "kapan-kavart", "kapan-aghbyur", "goris-center", "goris-verin-goris", "goris-aghbyur", "goris-davit-bek", "goris-syunik", "sisian-center", "sisian-arevik", "sisian-norashen", "sisian-sisakan", "kajaran-center", "kajaran-norashen", "kajaran-lernayin", "meghri-center", "meghri-prkashen", "meghri-mets-tagh", "agarak-center", "agarak-gortsaranayin", "dastakert-center", "tatev-center", "tatev-vorotan-gorge", "khndzoresk-center", "khndzoresk-hin-khndzoresk", "shinuhayr-center"];
export const sortKeyValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SortKey"]> = ["relevant", "date-desc", "price-asc", "price-desc"];
export const propertySubcategoryValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PropertySubcategory"]> = ["apartments", "houses", "new-buildings", "commercial", "land", "garages", "hotels", "guesthouses"];
export const dealValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Deal"]> = ["sale", "rent", "daily"];
export const propertyConditionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PropertyCondition"]> = ["euro", "renovated", "good", "needs-repair", "shell"];
export const buildingTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["BuildingType"]> = ["new", "secondary"];
export const propertySortKeyValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PropertySortKey"]> = ["relevant", "date-desc", "price-asc", "price-desc", "area-desc"];
export const roomsOptionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RoomsOption"]> = ["0", "1", "2", "3", "4"];
export const landTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LandType"]> = ["residential", "agricultural", "commercial", "industrial", "recreational"];
export const createUploadUrlRequestContentTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CreateUploadUrlRequest"]["contentType"]> = ["image/jpeg", "image/png", "image/webp"];
export const createUploadUrlRequestPurposeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CreateUploadUrlRequest"]["purpose"]> = ["listing", "avatar"];
export const componentsParametersWithPhotoValues: ReadonlyArray<FlattenedDeepRequired<components>["parameters"]["withPhoto"]> = ["1", "true", "0", "false"];
export const componentsParametersVerifiedOnlyValues: ReadonlyArray<FlattenedDeepRequired<components>["parameters"]["verifiedOnly"]> = ["1", "true", "0", "false"];
export const componentsParametersFurnitureValues: ReadonlyArray<FlattenedDeepRequired<components>["parameters"]["furniture"]> = ["1", "true", "0", "false"];
export const componentsParametersBalconyValues: ReadonlyArray<FlattenedDeepRequired<components>["parameters"]["balcony"]> = ["1", "true", "0", "false"];
export const componentsParametersParkingValues: ReadonlyArray<FlattenedDeepRequired<components>["parameters"]["parking"]> = ["1", "true", "0", "false"];
export const componentsParametersPoolValues: ReadonlyArray<FlattenedDeepRequired<components>["parameters"]["pool"]> = ["1", "true", "0", "false"];
