import type { CatalogCard, PropertyListing } from "@/lib/api/types";

export const PROPERTY_FIXTURE: PropertyListing = {
  id: "947e6113-f009-5717-a2f7-97b482ec8acf",
  category: "property",
  subcategory: "apartments",
  deal: "rent",
  title: "2-սենյականոց բնակարան Կապանի կենտրոնում",
  description: "Լուսավոր բնակարան կենտրոնում։",
  price: { amount: 300, currency: "USD", period: "month", negotiable: false },
  city: "kapan",
  district: "kapan-center",
  address: "Շահումյան փող., 8",
  coords: { lat: 39.2076, lng: 46.4057 },
  images: ["https://images.unsplash.com/photo-1.jpg", "https://images.unsplash.com/photo-2.jpg"],
  featured: false,
  verified: true,
  status: "active",
  publishedAt: "2026-09-01T10:00:00Z",
  seller: {
    id: "95a6aab5-87ff-57e9-a8ac-71b8f63283f3",
    name: "Արթուր Մկրտչյան",
    type: "private",
    phone: "+37491452218",
    hasWhatsApp: true,
    hasTelegram: false,
    hasViber: true,
    memberSince: "2021-04-12T10:00:00Z",
  },
  rooms: 2,
  area: 60,
  floor: 3,
  totalFloors: 5,
  bathrooms: 1,
  condition: "good",
  buildingType: "secondary",
  furniture: true,
  balcony: false,
  parking: true,
  pool: false,
};

export function catalogFixture(overrides: Partial<CatalogCard> = {}): CatalogCard {
  return {
    id: PROPERTY_FIXTURE.id,
    sellerId: PROPERTY_FIXTURE.seller!.id,
    category: "property",
    subcategory: "apartments",
    title: PROPERTY_FIXTURE.title,
    price: PROPERTY_FIXTURE.price,
    city: "kapan",
    district: "kapan-center",
    coverImage: PROPERTY_FIXTURE.images[0],
    imageCount: 2,
    featured: false,
    verified: true,
    status: "active",
    publishedAt: PROPERTY_FIXTURE.publishedAt,
    card: { deal: "rent", rooms: 2, area: 60 },
    ...overrides,
  };
}
